name: Compare PNG Files

on:
  pull_request:
    paths:
      - '**/*.png'

permissions:
  pull-requests: write

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find PNG files
        id: find_pngs
        run: |
          inside_file=$(find .open -name '*.png' | head -n 1)
          outside_file=$(find . -name '*.png' ! -path './.open/*' | head -n 1)

          echo "inside_file=$inside_file" >> $GITHUB_ENV
          echo "outside_file=$outside_file" >> $GITHUB_ENV

      - name: Compare PNG files
        id: compare
        run: |
          inside_file="${{ env.inside_file }}"
          outside_file="${{ env.outside_file }}"

          if [ -z "$inside_file" ] || [ -z "$outside_file" ]; then
            echo "One or both of the PNG files were not found."
            exit 1
          fi

          hex_inside=$(xxd -p "$inside_file" | tr -d '\n')
          hex_outside=$(xxd -p "$outside_file" | tr -d '\n')

          if [ "$hex_inside" != "$hex_outside" ]; then
            echo "The PNG files are not equal."
            echo "success=false" >> $GITHUB_ENV
            exit 1
          else
            echo "The PNG files are equal."
            echo "success=true" >> $GITHUB_ENV
          fi

      - name: Debugging output
        run: echo "success is ${{ env.success }}"

      - name: Post comment on PR
        if: env.success == 'true'
        run: |
          body=$(cat <<EOF
          {
            "body": "Congrats, Hero! 🦇\\n\\nYou have completed your mission! Gotham is safer thanks to your efforts. Now, for the next level, gear up and head to: [Shell-Shocks](https://github.com/JATAYU000/Shell-Shocks)\\n\\nStay vigilant!"
          }
          EOF
          )

          echo "Posting comment: $body"  # Debugging output

          response=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d "$body")

          echo "Response: $response"  # Debugging output
          cat response.json  # Output the response body for additional context

          if [ "$response" != "201" ]; then
            echo "Failed to post comment on PR: $response"
            exit 1
          fi
