name: Compare PNG Files

on:
  pull_request:
    paths:
      - '**/*.png'

jobs:
  compare:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find PNG files
        id: find_pngs
        run: |
          # Find PNG files in the repository and filter out the .open directory
          inside_file=$(find .open -name '*.png' | head -n 1)
          outside_file=$(find . -name '*.png' ! -path './.open/*' | head -n 1)

          echo "inside_file=$inside_file" >> $GITHUB_ENV
          echo "outside_file=$outside_file" >> $GITHUB_ENV

      - name: Compare PNG files
        id: compare
        run: |
          inside_file="${{ env.inside_file }}"
          outside_file="${{ env.outside_file }}"

          if [ -z "$inside_file" ] || [ -z "$outside_file" ]; then
            echo "One or both of the PNG files were not found."
            exit 1
          fi

          # Compare the hex values of the two files
          hex_inside=$(xxd -p "$inside_file" | tr -d '\n')
          hex_outside=$(xxd -p "$outside_file" | tr -d '\n')

          if [ "$hex_inside" != "$hex_outside" ]; then
            echo "The PNG files are not equal."
            echo "success=false" >> $GITHUB_ENV
            exit 1
          else
            echo "The PNG files are equal."
            echo "success=true" >> $GITHUB_ENV
          fi

      - name: Debugging output
        run: echo "success is ${{ env.success }}"

      - name: Post comment on PR
        if: env.success == 'true'
        run: |
          response=$(curl -s -o response.json -w "%{http_code}" -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments \
          -d '{"body": "The PNG files are equal. You can view the example URL here: https://example.com"}')

          if [ "$response" != "201" ]; then
            echo "Failed to post comment on PR: $response"
            exit 1
          fi
